rabbitmq.injector.scheduler.directory.query.interval=3600
rabbitmq.injector.scheduler.component.sniff.interval=60
ariane.community.injector.gears.registry.name=Ariane RabbitMQ plugin gears registry
ariane.community.injector.gears.registry.cache.id=ariane.community.plugin.rabbitmq.gears.cache
ariane.community.injector.gears.registry.cache.name=Ariane RabbitMQ plugin gears cache
ariane.community.injector.gears.cache.configuration.path=%%VIRGO_HOME/ariane/cache/plugins/rabbitmq/infinispan.gears.cache.xml
ariane.community.injector.components.registry.name=Ariane RabbitMQ plugin components registry
ariane.community.injector.components.registry.cache.id=ariane.community.plugin.rabbitmq.components.cache
ariane.community.injector.components.registry.cache.name=Ariane RabbitMQ plugin components cache
ariane.community.injector.components.cache.configuration.path=%%VIRGO_HOME/ariane/cache/plugins/rabbitmq/infinispan.components.cache.xml
